import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage(), errors=[];
page.on('pageerror',e=>errors.push(e.message));
const output=process.env.QA_OUTPUT_DIR||path.resolve('.qa-output');
await mkdir(output,{recursive:true});
const original=await (await fetch('http://127.0.0.1:3000/api/book')).json();
const shot=async name=>page.screenshot({path:path.join(output,`${name}.png`)});
const pause=ms=>page.waitForTimeout(ms);
try{
  await page.goto('http://127.0.0.1:3000',{waitUntil:'networkidle'});
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('#book').count(),1);
  assert.ok(await page.evaluate(()=>document.fonts.check('24px "TT Marxiana"')));
  await shot('reader-1440');
  await page.setViewportSize({width:1920,height:1200});await shot('reader-1920');
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:'Оглавление',exact:true}).click();await pause(550);
  assert.equal(await page.locator('#panel-title').textContent(),'ОГЛАВЛЕНИЕ.');
  await shot('toc');
  await page.getByRole('link',{name:'Распространение пчеловодства.'}).click();await pause(550);
  assert.ok(await page.evaluate(()=>scrollY)>1000);
  await page.getByRole('button',{name:'Редактировать оглавление',exact:true}).click();
  const title=page.getByRole('textbox',{name:'Название: Предварительные сведения.'});
  await title.fill('Проверенное оглавление');await title.press('Tab');await pause(450);
  await page.reload({waitUntil:'networkidle'});await page.keyboard.press('c');await pause(500);
  assert.equal(await page.getByRole('link',{name:'Проверенное оглавление'}).count(),1);
  await page.getByRole('button',{name:'Редактировать оглавление',exact:true}).click();
  await page.getByRole('button',{name:'Скрыть пункт: Предварительные сведения.'}).click();await pause(400);
  await page.getByRole('button',{name:'Редактировать оглавление',exact:true}).click();
  assert.equal(await page.getByRole('link',{name:'Проверенное оглавление'}).count(),0);
  await page.getByRole('button',{name:'Редактировать оглавление',exact:true}).click();
  await page.getByRole('button',{name:'Сбросить ручную правку: Предварительные сведения.'}).click();await pause(350);
  await page.getByRole('button',{name:'Закрыть панель',exact:true}).click();
  // Real pointer drag over a line, using text geometry only for locating endpoints.
  await page.locator('#honey').scrollIntoViewIfNeeded();
  const points=await page.locator('#honey').evaluate(el=>{
    const text=el.firstChild,r=document.createRange();r.setStart(text,0);r.setEnd(text,52);
    const rects=[...r.getClientRects()];
    const a=rects[0],b=rects.at(-1);return {x1:a.x+1,y1:a.y+a.height/2,x2:b.right-1,y2:b.y+b.height/2};
  });
  await page.mouse.move(points.x1,points.y1);await page.mouse.down();await page.mouse.move(points.x2,points.y2,{steps:20});await page.mouse.up();await pause(200);
  assert.ok(await page.getByRole('button',{name:'В заметки',exact:true}).isVisible());
  await page.getByRole('button',{name:'В заметки',exact:true}).click();await pause(500);
  assert.ok(await page.locator('#honey mark').count()>0);
  await page.keyboard.press('b');await pause(550);await shot('notes');
  assert.ok(await page.locator('.note-link').count()>0);
  await page.locator('.note-link').first().click();await pause(400);
  await page.reload({waitUntil:'networkidle'});
  assert.ok(await page.locator('#honey mark').count()>0);
  await page.locator('#future').scrollIntoViewIfNeeded();
  await page.getByRole('button',{name:'Поставить закладку',exact:true}).click();await pause(650);
  assert.ok(await page.getByRole('button',{name:'Вернуться к закладке',exact:true}).isVisible());
  await page.reload({waitUntil:'networkidle'});
  assert.ok(await page.getByRole('button',{name:'Вернуться к закладке',exact:true}).isVisible());
  await page.locator('#garden').scrollIntoViewIfNeeded();
  await page.getByRole('button',{name:'Поставить закладку',exact:true}).click();await pause(1200);
  await page.keyboard.press('Control+Home');await pause(300);
  await shot('bookmark');
  await page.getByRole('button',{name:'Вернуться к закладке',exact:true}).click();await pause(1100);
  assert.ok(await page.evaluate(()=>scrollY)>1000);
  assert.ok(await page.getByRole('button',{name:'Вернуться к закладке',exact:true}).isHidden());
  await page.keyboard.press('e');await pause(300);
  assert.equal(await page.locator('#book').getAttribute('contenteditable'),'true');
  await page.locator('#garden').click();await page.keyboard.press('End');await page.keyboard.type(' QA-check');
  await page.keyboard.press('Control+s');await pause(1000);
  assert.equal(await page.locator('#save-status').textContent(),'Сохранено');
  await page.keyboard.press('Escape');await pause(400);
  await page.reload({waitUntil:'networkidle'});
  assert.match(await page.locator('#garden').textContent(),/QA-check/);
  await page.keyboard.press('e');await pause(200);
  await page.keyboard.press('Control+Home');await pause(200);await shot('editor');
  // Native style application with real selection.
  await page.locator('#france').click();await page.keyboard.press('Home');await page.keyboard.press('Shift+End');
  await page.getByRole('combobox',{name:'Стиль текста',exact:true}).selectOption('small');
  await pause(1100);
  assert.ok(await page.locator('#france').evaluate(el=>el.classList.contains('small')));
  await page.getByRole('combobox',{name:'Стиль текста',exact:true}).selectOption('p');
  await page.getByRole('button',{name:'Параметры текста',exact:true}).click();
  await page.getByLabel('Размер, rem',{exact:true}).fill('2.1');
  await page.getByLabel('Интерлиньяж, rem',{exact:true}).fill('2.3');
  await page.getByLabel('Красная строка, rem',{exact:true}).fill('2.5');
  await page.getByRole('button',{name:'Применить',exact:true}).click();await pause(1100);
  assert.match(await page.locator('#france').getAttribute('style'),/2.1rem/);
  await page.locator('#france').click();await page.keyboard.press('End');
  await page.locator('#image-input').setInputFiles('data/books/bees/img/frontispiece.png');await pause(1300);
  const uploaded=page.locator('#book img:not(.frontispiece)');assert.equal(await uploaded.count(),1);
  await uploaded.click();await page.getByRole('button',{name:'Параметры текста',exact:true}).click();
  await page.getByLabel('Обтекание картинки').selectOption('wrap-left');
  await page.getByRole('button',{name:'Применить',exact:true}).click();await pause(1200);
  assert.match(await uploaded.getAttribute('class'),/wrap-left/);
  await page.keyboard.press('Escape');await pause(400);
  await page.keyboard.press('Control+Home');await pause(300);
  await page.locator('.rail').hover();await page.getByRole('button',{name:'Сменить тему',exact:true}).click();await shot('dark');
  await page.getByRole('button',{name:'Сменить тему',exact:true}).click();
  await page.getByRole('button',{name:'Помощь',exact:true}).click();assert.ok(await page.locator('#help').isVisible());
  await page.getByRole('button',{name:'Закрыть',exact:true}).click();
  assert.deepEqual(errors,[]);
  console.log('PASS: desktop reader/fonts, TOC navigation/overrides/hide/reset, notes/create/reload, bookmark/move/reload/consume, editor/save/reload, styles/rem, image upload/wrapping, theme, help; no page errors.');
}finally{
  const latest=await (await fetch('http://127.0.0.1:3000/api/book')).json();
  await fetch('http://127.0.0.1:3000/api/book',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({html:original.html,revision:latest.revision})});
  await browser.close();
}
